kind: pipeline
name: docker-nginx

clone:
  disable: true

steps:
  - name: clone
    image: docker:git
    commands:
      - git clone $DRONE_REMOTE_URL
      - git checkout $DRONE_COMMIT


  - name: docker
    image: plugins/docker
    pull: always
    when:
      event:
        - pull_request
        - tag
    settings:
      repo: storezhang/nginx
      dockerfile: ./Dockerfile
      mirror: https://docker.mirrors.ustc.edu.cn
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      force_tag: true
