kind: pipeline
name: docker-nginx

clone:
  recursive: true

steps:
  - name: submodules
    image: docker:git
    commands:
      - ls modules/nginx-dav-ext-module


  - name: docker
    image: plugins/docker
    pull: always
    when:
      event:
        - pull_request
        - tag
    settings:
      repo: storezhang/nginx
      dockerfile: ./Dockerfile
      mirror: https://docker.mirrors.ustc.edu.cn
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      force_tag: true
