kind: pipeline
name: docker-nginx

clone:
  git:
    image: plugins/git
    recursive: true
    submodule_override:
      modules/headers-more-nginx-module: https://github.com/openresty/headers-more-nginx-module.git
      modules/nginx-dav-ext-module: https://github.com/arut/nginx-dav-ext-module.git

steps:
  - name: docker
    image: plugins/docker
    pull: always
    when:
      event:
        - pull_request
        - tag
    settings:
      repo: storezhang/nginx
      dockerfile: ./Dockerfile
      mirror: https://docker.mirrors.ustc.edu.cn
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      force_tag: true
